// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_runtime_controls
Rcpp::List cpp_runtime_controls();
RcppExport SEXP _rfugw_cpp_runtime_controls() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_runtime_controls());
    return rcpp_result_gen;
END_RCPP
}
// cpp_fgw_entropic_square
Rcpp::List cpp_fgw_entropic_square(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, const arma::vec& q, double alpha, double epsilon, int max_iter, double tol, int sinkhorn_max_iter, double sinkhorn_tol, bool symmetric, bool use_ppa, bool use_log_sinkhorn, bool use_mixed_precision, int check_every, int approx_rank, const arma::mat& init_plan, bool allow_double_mixed_accel);
RcppExport SEXP _rfugw_cpp_fgw_entropic_square(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP sinkhorn_max_iterSEXP, SEXP sinkhorn_tolSEXP, SEXP symmetricSEXP, SEXP use_ppaSEXP, SEXP use_log_sinkhornSEXP, SEXP use_mixed_precisionSEXP, SEXP check_everySEXP, SEXP approx_rankSEXP, SEXP init_planSEXP, SEXP allow_double_mixed_accelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type sinkhorn_max_iter(sinkhorn_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type sinkhorn_tol(sinkhorn_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ppa(use_ppaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_log_sinkhorn(use_log_sinkhornSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< int >::type approx_rank(approx_rankSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_double_mixed_accel(allow_double_mixed_accelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fgw_entropic_square(M, C1, C2, p, q, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, approx_rank, init_plan, allow_double_mixed_accel));
    return rcpp_result_gen;
END_RCPP
}
// cpp_entropic_semirelaxed_fgw_square
Rcpp::List cpp_entropic_semirelaxed_fgw_square(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, double epsilon, double alpha, bool symmetric, bool use_mixed_precision, int max_iter, double tol, int check_every, const arma::mat& init_plan);
RcppExport SEXP _rfugw_cpp_entropic_semirelaxed_fgw_square(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP epsilonSEXP, SEXP alphaSEXP, SEXP symmetricSEXP, SEXP use_mixed_precisionSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP check_everySEXP, SEXP init_planSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_entropic_semirelaxed_fgw_square(M, C1, C2, p, epsilon, alpha, symmetric, use_mixed_precision, max_iter, tol, check_every, init_plan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fgw_entropic_square_batch
Rcpp::List cpp_fgw_entropic_square_batch(const Rcpp::List& M_list, const Rcpp::List& C1_list, const Rcpp::List& p_list, const arma::mat& C2, const arma::vec& q, double alpha, double epsilon, int max_iter, double tol, int sinkhorn_max_iter, double sinkhorn_tol, bool symmetric, bool use_ppa, bool use_log_sinkhorn, bool use_mixed_precision, int check_every, const Rcpp::List& init_plan_list, const Rcpp::List& c1_A_scaled_list, const Rcpp::List& c1_Bt_list, int approx_rank, int n_threads, bool allow_double_mixed_accel);
RcppExport SEXP _rfugw_cpp_fgw_entropic_square_batch(SEXP M_listSEXP, SEXP C1_listSEXP, SEXP p_listSEXP, SEXP C2SEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP sinkhorn_max_iterSEXP, SEXP sinkhorn_tolSEXP, SEXP symmetricSEXP, SEXP use_ppaSEXP, SEXP use_log_sinkhornSEXP, SEXP use_mixed_precisionSEXP, SEXP check_everySEXP, SEXP init_plan_listSEXP, SEXP c1_A_scaled_listSEXP, SEXP c1_Bt_listSEXP, SEXP approx_rankSEXP, SEXP n_threadsSEXP, SEXP allow_double_mixed_accelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type M_list(M_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type C1_list(C1_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type p_list(p_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type sinkhorn_max_iter(sinkhorn_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type sinkhorn_tol(sinkhorn_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ppa(use_ppaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_log_sinkhorn(use_log_sinkhornSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init_plan_list(init_plan_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type c1_A_scaled_list(c1_A_scaled_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type c1_Bt_list(c1_Bt_listSEXP);
    Rcpp::traits::input_parameter< int >::type approx_rank(approx_rankSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_double_mixed_accel(allow_double_mixed_accelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fgw_entropic_square_batch(M_list, C1_list, p_list, C2, q, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, init_plan_list, c1_A_scaled_list, c1_Bt_list, approx_rank, n_threads, allow_double_mixed_accel));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fgw_entropic_square_batch_features
Rcpp::List cpp_fgw_entropic_square_batch_features(const Rcpp::List& F1_list, const Rcpp::List& C1_list, const Rcpp::List& p_list, const arma::mat& F2, const arma::mat& C2, const arma::vec& q, bool use_euclidean, bool rescale01, double alpha, double epsilon, int max_iter, double tol, int sinkhorn_max_iter, double sinkhorn_tol, bool symmetric, bool use_ppa, bool use_log_sinkhorn, bool use_mixed_precision, int check_every, const Rcpp::List& init_plan_list, const Rcpp::List& c1_A_scaled_list, const Rcpp::List& c1_Bt_list, int approx_rank, int n_threads, bool allow_double_mixed_accel);
RcppExport SEXP _rfugw_cpp_fgw_entropic_square_batch_features(SEXP F1_listSEXP, SEXP C1_listSEXP, SEXP p_listSEXP, SEXP F2SEXP, SEXP C2SEXP, SEXP qSEXP, SEXP use_euclideanSEXP, SEXP rescale01SEXP, SEXP alphaSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP sinkhorn_max_iterSEXP, SEXP sinkhorn_tolSEXP, SEXP symmetricSEXP, SEXP use_ppaSEXP, SEXP use_log_sinkhornSEXP, SEXP use_mixed_precisionSEXP, SEXP check_everySEXP, SEXP init_plan_listSEXP, SEXP c1_A_scaled_listSEXP, SEXP c1_Bt_listSEXP, SEXP approx_rankSEXP, SEXP n_threadsSEXP, SEXP allow_double_mixed_accelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type F1_list(F1_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type C1_list(C1_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type p_list(p_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F2(F2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type use_euclidean(use_euclideanSEXP);
    Rcpp::traits::input_parameter< bool >::type rescale01(rescale01SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type sinkhorn_max_iter(sinkhorn_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type sinkhorn_tol(sinkhorn_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ppa(use_ppaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_log_sinkhorn(use_log_sinkhornSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init_plan_list(init_plan_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type c1_A_scaled_list(c1_A_scaled_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type c1_Bt_list(c1_Bt_listSEXP);
    Rcpp::traits::input_parameter< int >::type approx_rank(approx_rankSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_double_mixed_accel(allow_double_mixed_accelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fgw_entropic_square_batch_features(F1_list, C1_list, p_list, F2, C2, q, use_euclidean, rescale01, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, init_plan_list, c1_A_scaled_list, c1_Bt_list, approx_rank, n_threads, allow_double_mixed_accel));
    return rcpp_result_gen;
END_RCPP
}
// cpp_feature_cost_batch
Rcpp::List cpp_feature_cost_batch(const Rcpp::List& F1_list, const arma::mat& F2, bool use_euclidean, bool rescale01, int n_threads);
RcppExport SEXP _rfugw_cpp_feature_cost_batch(SEXP F1_listSEXP, SEXP F2SEXP, SEXP use_euclideanSEXP, SEXP rescale01SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type F1_list(F1_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F2(F2SEXP);
    Rcpp::traits::input_parameter< bool >::type use_euclidean(use_euclideanSEXP);
    Rcpp::traits::input_parameter< bool >::type rescale01(rescale01SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_feature_cost_batch(F1_list, F2, use_euclidean, rescale01, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fgw_exact_cg_square
Rcpp::List cpp_fgw_exact_cg_square(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, const arma::vec& q, double alpha, bool symmetric, int max_iter, double tol_rel, double tol_abs, int lp_max_iter, double lp_tol, const arma::mat& init_plan);
RcppExport SEXP _rfugw_cpp_fgw_exact_cg_square(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP symmetricSEXP, SEXP max_iterSEXP, SEXP tol_relSEXP, SEXP tol_absSEXP, SEXP lp_max_iterSEXP, SEXP lp_tolSEXP, SEXP init_planSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< int >::type lp_max_iter(lp_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lp_tol(lp_tolSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fgw_exact_cg_square(M, C1, C2, p, q, alpha, symmetric, max_iter, tol_rel, tol_abs, lp_max_iter, lp_tol, init_plan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fugw_kl_square
Rcpp::List cpp_fugw_kl_square(const arma::mat& Cx, const arma::mat& Cy, const arma::vec& wx, const arma::vec& wy, const arma::vec& reg_marginals, double epsilon, double alpha, const arma::mat& M, const arma::mat& init_pi, int max_iter, double tol, int max_iter_ot, double tol_ot, bool rescale_plan, int check_every, bool use_mixed_precision);
RcppExport SEXP _rfugw_cpp_fugw_kl_square(SEXP CxSEXP, SEXP CySEXP, SEXP wxSEXP, SEXP wySEXP, SEXP reg_marginalsSEXP, SEXP epsilonSEXP, SEXP alphaSEXP, SEXP MSEXP, SEXP init_piSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP max_iter_otSEXP, SEXP tol_otSEXP, SEXP rescale_planSEXP, SEXP check_everySEXP, SEXP use_mixed_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Cx(CxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Cy(CySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wx(wxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wy(wySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type reg_marginals(reg_marginalsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_pi(init_piSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_ot(max_iter_otSEXP);
    Rcpp::traits::input_parameter< double >::type tol_ot(tol_otSEXP);
    Rcpp::traits::input_parameter< bool >::type rescale_plan(rescale_planSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fugw_kl_square(Cx, Cy, wx, wy, reg_marginals, epsilon, alpha, M, init_pi, max_iter, tol, max_iter_ot, tol_ot, rescale_plan, check_every, use_mixed_precision));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fugw_kl_square_batch
Rcpp::List cpp_fugw_kl_square_batch(const Rcpp::List& Cx_list, const Rcpp::List& wx_list, const Rcpp::List& M_list, const arma::mat& Cy, const arma::vec& wy, const arma::vec& reg_marginals, double epsilon, double alpha, int max_iter, double tol, int max_iter_ot, double tol_ot, bool rescale_plan, int check_every, const Rcpp::List& init_pi_list, int n_threads);
RcppExport SEXP _rfugw_cpp_fugw_kl_square_batch(SEXP Cx_listSEXP, SEXP wx_listSEXP, SEXP M_listSEXP, SEXP CySEXP, SEXP wySEXP, SEXP reg_marginalsSEXP, SEXP epsilonSEXP, SEXP alphaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP max_iter_otSEXP, SEXP tol_otSEXP, SEXP rescale_planSEXP, SEXP check_everySEXP, SEXP init_pi_listSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Cx_list(Cx_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wx_list(wx_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type M_list(M_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Cy(CySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wy(wySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type reg_marginals(reg_marginalsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_ot(max_iter_otSEXP);
    Rcpp::traits::input_parameter< double >::type tol_ot(tol_otSEXP);
    Rcpp::traits::input_parameter< bool >::type rescale_plan(rescale_planSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type init_pi_list(init_pi_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fugw_kl_square_batch(Cx_list, wx_list, M_list, Cy, wy, reg_marginals, epsilon, alpha, max_iter, tol, max_iter_ot, tol_ot, rescale_plan, check_every, init_pi_list, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sampled_gromov_wasserstein_entropic_square
Rcpp::List cpp_sampled_gromov_wasserstein_entropic_square(const arma::mat& C1, const arma::mat& C2, const arma::vec& p, const arma::vec& q, int nb_p, int nb_q, double epsilon, int max_iter, int sinkhorn_max_iter, double sinkhorn_tol, bool symmetric, const arma::mat& init_plan, bool verbose, bool use_mixed_precision);
RcppExport SEXP _rfugw_cpp_sampled_gromov_wasserstein_entropic_square(SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP qSEXP, SEXP nb_pSEXP, SEXP nb_qSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP sinkhorn_max_iterSEXP, SEXP sinkhorn_tolSEXP, SEXP symmetricSEXP, SEXP init_planSEXP, SEXP verboseSEXP, SEXP use_mixed_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nb_p(nb_pSEXP);
    Rcpp::traits::input_parameter< int >::type nb_q(nb_qSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type sinkhorn_max_iter(sinkhorn_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type sinkhorn_tol(sinkhorn_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sampled_gromov_wasserstein_entropic_square(C1, C2, p, q, nb_p, nb_q, epsilon, max_iter, sinkhorn_max_iter, sinkhorn_tol, symmetric, init_plan, verbose, use_mixed_precision));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sampled_gromov_wasserstein_coords_entropic_square
Rcpp::List cpp_sampled_gromov_wasserstein_coords_entropic_square(const arma::mat& X1, const arma::mat& X2, const arma::vec& p, const arma::vec& q, int nb_p, int nb_q, double epsilon, int max_iter, int sinkhorn_max_iter, double sinkhorn_tol, int metric_code, const arma::mat& init_plan, bool verbose, bool use_mixed_precision, bool deterministic_sampling);
RcppExport SEXP _rfugw_cpp_sampled_gromov_wasserstein_coords_entropic_square(SEXP X1SEXP, SEXP X2SEXP, SEXP pSEXP, SEXP qSEXP, SEXP nb_pSEXP, SEXP nb_qSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP sinkhorn_max_iterSEXP, SEXP sinkhorn_tolSEXP, SEXP metric_codeSEXP, SEXP init_planSEXP, SEXP verboseSEXP, SEXP use_mixed_precisionSEXP, SEXP deterministic_samplingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nb_p(nb_pSEXP);
    Rcpp::traits::input_parameter< int >::type nb_q(nb_qSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type sinkhorn_max_iter(sinkhorn_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type sinkhorn_tol(sinkhorn_tolSEXP);
    Rcpp::traits::input_parameter< int >::type metric_code(metric_codeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    Rcpp::traits::input_parameter< bool >::type deterministic_sampling(deterministic_samplingSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sampled_gromov_wasserstein_coords_entropic_square(X1, X2, p, q, nb_p, nb_q, epsilon, max_iter, sinkhorn_max_iter, sinkhorn_tol, metric_code, init_plan, verbose, use_mixed_precision, deterministic_sampling));
    return rcpp_result_gen;
END_RCPP
}
// cpp_srfgw_row_min_direction
arma::mat cpp_srfgw_row_min_direction(const arma::mat& Mi, const arma::vec& p);
RcppExport SEXP _rfugw_cpp_srfgw_row_min_direction(SEXP MiSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Mi(MiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_srfgw_row_min_direction(Mi, p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_entropic_partial_wasserstein
SEXP cpp_entropic_partial_wasserstein(const arma::vec& a, const arma::vec& b, const arma::mat& M, double reg, double m, int numItermax, double stopThr, bool verbose, bool log);
RcppExport SEXP _rfugw_cpp_entropic_partial_wasserstein(SEXP aSEXP, SEXP bSEXP, SEXP MSEXP, SEXP regSEXP, SEXP mSEXP, SEXP numItermaxSEXP, SEXP stopThrSEXP, SEXP verboseSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type numItermax(numItermaxSEXP);
    Rcpp::traits::input_parameter< double >::type stopThr(stopThrSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_entropic_partial_wasserstein(a, b, M, reg, m, numItermax, stopThr, verbose, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_semirelaxed_fgw_exact_square
Rcpp::List cpp_semirelaxed_fgw_exact_square(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, double alpha, bool symmetric, const arma::mat& init_plan, int max_iter, double tol_rel, double tol_abs);
RcppExport SEXP _rfugw_cpp_semirelaxed_fgw_exact_square(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP alphaSEXP, SEXP symmetricSEXP, SEXP init_planSEXP, SEXP max_iterSEXP, SEXP tol_relSEXP, SEXP tol_absSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< double >::type tol_abs(tol_absSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_semirelaxed_fgw_exact_square(M, C1, C2, p, alpha, symmetric, init_plan, max_iter, tol_rel, tol_abs));
    return rcpp_result_gen;
END_RCPP
}
// cpp_semirelaxed_fgw_cg_square_fast
Rcpp::List cpp_semirelaxed_fgw_cg_square_fast(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, double alpha, const arma::mat& init_plan, int max_iter, double tol_rel, double tol_abs, bool verbose, bool use_mixed_precision);
RcppExport SEXP _rfugw_cpp_semirelaxed_fgw_cg_square_fast(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP alphaSEXP, SEXP init_planSEXP, SEXP max_iterSEXP, SEXP tol_relSEXP, SEXP tol_absSEXP, SEXP verboseSEXP, SEXP use_mixed_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mixed_precision(use_mixed_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_semirelaxed_fgw_cg_square_fast(M, C1, C2, p, alpha, init_plan, max_iter, tol_rel, tol_abs, verbose, use_mixed_precision));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ot_sinkhorn
Rcpp::List cpp_ot_sinkhorn(const arma::mat& M, const arma::vec& p, const arma::vec& q, double epsilon, int max_iter, double tol, bool use_log);
RcppExport SEXP _rfugw_cpp_ot_sinkhorn(SEXP MSEXP, SEXP pSEXP, SEXP qSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP use_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type use_log(use_logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ot_sinkhorn(M, p, q, epsilon, max_iter, tol, use_log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ot_emd
Rcpp::List cpp_ot_emd(const arma::mat& M, const arma::vec& p, const arma::vec& q, int max_iter, double tol);
RcppExport SEXP _rfugw_cpp_ot_emd(SEXP MSEXP, SEXP pSEXP, SEXP qSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ot_emd(M, p, q, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_transport_simplex_test
Rcpp::List cpp_transport_simplex_test(const arma::mat& M, const arma::vec& p, const arma::vec& q, int max_iter, double tol, std::string inject_failure);
RcppExport SEXP _rfugw_cpp_transport_simplex_test(SEXP MSEXP, SEXP pSEXP, SEXP qSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP inject_failureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type inject_failure(inject_failureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_transport_simplex_test(M, p, q, max_iter, tol, inject_failure));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ot_sinkhorn_unbalanced
Rcpp::List cpp_ot_sinkhorn_unbalanced(const arma::mat& M, const arma::vec& a, const arma::vec& b, double epsilon, double rho1, double rho2, int max_iter, double tol, const arma::mat& init_plan);
RcppExport SEXP _rfugw_cpp_ot_sinkhorn_unbalanced(SEXP MSEXP, SEXP aSEXP, SEXP bSEXP, SEXP epsilonSEXP, SEXP rho1SEXP, SEXP rho2SEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP init_planSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ot_sinkhorn_unbalanced(M, a, b, epsilon, rho1, rho2, max_iter, tol, init_plan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partial_fgw_exact_square
Rcpp::List cpp_partial_fgw_exact_square(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, const arma::vec& q, double m, double alpha, bool symmetric, const arma::mat& init_plan, int max_iter, double tol, int nb_dummies, int lp_max_iter, double lp_tol, std::string test_inner_failure);
RcppExport SEXP _rfugw_cpp_partial_fgw_exact_square(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP qSEXP, SEXP mSEXP, SEXP alphaSEXP, SEXP symmetricSEXP, SEXP init_planSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP nb_dummiesSEXP, SEXP lp_max_iterSEXP, SEXP lp_tolSEXP, SEXP test_inner_failureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type nb_dummies(nb_dummiesSEXP);
    Rcpp::traits::input_parameter< int >::type lp_max_iter(lp_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lp_tol(lp_tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type test_inner_failure(test_inner_failureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partial_fgw_exact_square(M, C1, C2, p, q, m, alpha, symmetric, init_plan, max_iter, tol, nb_dummies, lp_max_iter, lp_tol, test_inner_failure));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partial_fgw_entropic_square
Rcpp::List cpp_partial_fgw_entropic_square(const arma::mat& M, const arma::mat& C1, const arma::mat& C2, const arma::vec& p, const arma::vec& q, double m, double reg, double alpha, bool symmetric, const arma::mat& init_plan, int max_iter, double tol, int inner_max_iter, double inner_tol, int check_every);
RcppExport SEXP _rfugw_cpp_partial_fgw_entropic_square(SEXP MSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP pSEXP, SEXP qSEXP, SEXP mSEXP, SEXP regSEXP, SEXP alphaSEXP, SEXP symmetricSEXP, SEXP init_planSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP inner_max_iterSEXP, SEXP inner_tolSEXP, SEXP check_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type reg(regSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_plan(init_planSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type inner_max_iter(inner_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< int >::type check_every(check_everySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partial_fgw_entropic_square(M, C1, C2, p, q, m, reg, alpha, symmetric, init_plan, max_iter, tol, inner_max_iter, inner_tol, check_every));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ucoot_kl
Rcpp::List cpp_ucoot_kl(const arma::mat& X, const arma::mat& Y, const arma::vec& wx_samp, const arma::vec& wx_feat, const arma::vec& wy_samp, const arma::vec& wy_feat, const arma::vec& reg_marginals, const arma::vec& epsilon, const arma::mat& M_samp, const arma::mat& M_feat, const arma::mat& init_pi_samp, const arma::mat& init_pi_feat, bool joint, bool rescale_plan, int max_iter, double tol, int max_iter_ot, double tol_ot, bool use_warm_start);
RcppExport SEXP _rfugw_cpp_ucoot_kl(SEXP XSEXP, SEXP YSEXP, SEXP wx_sampSEXP, SEXP wx_featSEXP, SEXP wy_sampSEXP, SEXP wy_featSEXP, SEXP reg_marginalsSEXP, SEXP epsilonSEXP, SEXP M_sampSEXP, SEXP M_featSEXP, SEXP init_pi_sampSEXP, SEXP init_pi_featSEXP, SEXP jointSEXP, SEXP rescale_planSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP max_iter_otSEXP, SEXP tol_otSEXP, SEXP use_warm_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wx_samp(wx_sampSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wx_feat(wx_featSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wy_samp(wy_sampSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wy_feat(wy_featSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type reg_marginals(reg_marginalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M_samp(M_sampSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M_feat(M_featSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_pi_samp(init_pi_sampSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_pi_feat(init_pi_featSEXP);
    Rcpp::traits::input_parameter< bool >::type joint(jointSEXP);
    Rcpp::traits::input_parameter< bool >::type rescale_plan(rescale_planSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_ot(max_iter_otSEXP);
    Rcpp::traits::input_parameter< double >::type tol_ot(tol_otSEXP);
    Rcpp::traits::input_parameter< bool >::type use_warm_start(use_warm_startSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ucoot_kl(X, Y, wx_samp, wx_feat, wy_samp, wy_feat, reg_marginals, epsilon, M_samp, M_feat, init_pi_samp, init_pi_feat, joint, rescale_plan, max_iter, tol, max_iter_ot, tol_ot, use_warm_start));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gw_square_terms_square
Rcpp::List cpp_gw_square_terms_square(const arma::mat& C1, const arma::mat& C2, const arma::mat& G, bool symmetric);
RcppExport SEXP _rfugw_cpp_gw_square_terms_square(SEXP C1SEXP, SEXP C2SEXP, SEXP GSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gw_square_terms_square(C1, C2, G, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// cpp_thread_kernel_probe
Rcpp::List cpp_thread_kernel_probe(int n_jobs, int n_threads, int nested_threads, bool inject_failure);
RcppExport SEXP _rfugw_cpp_thread_kernel_probe(SEXP n_jobsSEXP, SEXP n_threadsSEXP, SEXP nested_threadsSEXP, SEXP inject_failureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_jobs(n_jobsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type nested_threads(nested_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type inject_failure(inject_failureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_thread_kernel_probe(n_jobs, n_threads, nested_threads, inject_failure));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rfugw_cpp_runtime_controls", (DL_FUNC) &_rfugw_cpp_runtime_controls, 0},
    {"_rfugw_cpp_fgw_entropic_square", (DL_FUNC) &_rfugw_cpp_fgw_entropic_square, 19},
    {"_rfugw_cpp_entropic_semirelaxed_fgw_square", (DL_FUNC) &_rfugw_cpp_entropic_semirelaxed_fgw_square, 12},
    {"_rfugw_cpp_fgw_entropic_square_batch", (DL_FUNC) &_rfugw_cpp_fgw_entropic_square_batch, 22},
    {"_rfugw_cpp_fgw_entropic_square_batch_features", (DL_FUNC) &_rfugw_cpp_fgw_entropic_square_batch_features, 25},
    {"_rfugw_cpp_feature_cost_batch", (DL_FUNC) &_rfugw_cpp_feature_cost_batch, 5},
    {"_rfugw_cpp_fgw_exact_cg_square", (DL_FUNC) &_rfugw_cpp_fgw_exact_cg_square, 13},
    {"_rfugw_cpp_fugw_kl_square", (DL_FUNC) &_rfugw_cpp_fugw_kl_square, 16},
    {"_rfugw_cpp_fugw_kl_square_batch", (DL_FUNC) &_rfugw_cpp_fugw_kl_square_batch, 16},
    {"_rfugw_cpp_sampled_gromov_wasserstein_entropic_square", (DL_FUNC) &_rfugw_cpp_sampled_gromov_wasserstein_entropic_square, 14},
    {"_rfugw_cpp_sampled_gromov_wasserstein_coords_entropic_square", (DL_FUNC) &_rfugw_cpp_sampled_gromov_wasserstein_coords_entropic_square, 15},
    {"_rfugw_cpp_srfgw_row_min_direction", (DL_FUNC) &_rfugw_cpp_srfgw_row_min_direction, 2},
    {"_rfugw_cpp_entropic_partial_wasserstein", (DL_FUNC) &_rfugw_cpp_entropic_partial_wasserstein, 9},
    {"_rfugw_cpp_semirelaxed_fgw_exact_square", (DL_FUNC) &_rfugw_cpp_semirelaxed_fgw_exact_square, 10},
    {"_rfugw_cpp_semirelaxed_fgw_cg_square_fast", (DL_FUNC) &_rfugw_cpp_semirelaxed_fgw_cg_square_fast, 11},
    {"_rfugw_cpp_ot_sinkhorn", (DL_FUNC) &_rfugw_cpp_ot_sinkhorn, 7},
    {"_rfugw_cpp_ot_emd", (DL_FUNC) &_rfugw_cpp_ot_emd, 5},
    {"_rfugw_cpp_transport_simplex_test", (DL_FUNC) &_rfugw_cpp_transport_simplex_test, 6},
    {"_rfugw_cpp_ot_sinkhorn_unbalanced", (DL_FUNC) &_rfugw_cpp_ot_sinkhorn_unbalanced, 9},
    {"_rfugw_cpp_partial_fgw_exact_square", (DL_FUNC) &_rfugw_cpp_partial_fgw_exact_square, 15},
    {"_rfugw_cpp_partial_fgw_entropic_square", (DL_FUNC) &_rfugw_cpp_partial_fgw_entropic_square, 15},
    {"_rfugw_cpp_ucoot_kl", (DL_FUNC) &_rfugw_cpp_ucoot_kl, 19},
    {"_rfugw_cpp_gw_square_terms_square", (DL_FUNC) &_rfugw_cpp_gw_square_terms_square, 4},
    {"_rfugw_cpp_thread_kernel_probe", (DL_FUNC) &_rfugw_cpp_thread_kernel_probe, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rfugw(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
