# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_fgw_entropic_square <- function(M, C1, C2, p, q, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, approx_rank, init_plan) {
    .Call(`_rfugw_cpp_fgw_entropic_square`, M, C1, C2, p, q, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, approx_rank, init_plan)
}

cpp_entropic_semirelaxed_fgw_square <- function(M, C1, C2, p, epsilon, alpha, symmetric, use_mixed_precision, max_iter, tol, check_every, init_plan) {
    .Call(`_rfugw_cpp_entropic_semirelaxed_fgw_square`, M, C1, C2, p, epsilon, alpha, symmetric, use_mixed_precision, max_iter, tol, check_every, init_plan)
}

cpp_fgw_entropic_square_batch <- function(M_list, C1_list, p_list, C2, q, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, init_plan_list, c1_A_scaled_list, c1_Bt_list, approx_rank, n_threads) {
    .Call(`_rfugw_cpp_fgw_entropic_square_batch`, M_list, C1_list, p_list, C2, q, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, init_plan_list, c1_A_scaled_list, c1_Bt_list, approx_rank, n_threads)
}

cpp_fgw_entropic_square_batch_features <- function(F1_list, C1_list, p_list, F2, C2, q, use_euclidean, rescale01, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, init_plan_list, c1_A_scaled_list, c1_Bt_list, approx_rank, n_threads) {
    .Call(`_rfugw_cpp_fgw_entropic_square_batch_features`, F1_list, C1_list, p_list, F2, C2, q, use_euclidean, rescale01, alpha, epsilon, max_iter, tol, sinkhorn_max_iter, sinkhorn_tol, symmetric, use_ppa, use_log_sinkhorn, use_mixed_precision, check_every, init_plan_list, c1_A_scaled_list, c1_Bt_list, approx_rank, n_threads)
}

cpp_feature_cost_batch <- function(F1_list, F2, use_euclidean, rescale01, n_threads) {
    .Call(`_rfugw_cpp_feature_cost_batch`, F1_list, F2, use_euclidean, rescale01, n_threads)
}

cpp_fgw_exact_cg_square <- function(M, C1, C2, p, q, alpha, symmetric, max_iter, tol_rel, tol_abs, lp_max_iter, lp_tol, init_plan) {
    .Call(`_rfugw_cpp_fgw_exact_cg_square`, M, C1, C2, p, q, alpha, symmetric, max_iter, tol_rel, tol_abs, lp_max_iter, lp_tol, init_plan)
}

cpp_fugw_kl_square <- function(Cx, Cy, wx, wy, reg_marginals, epsilon, alpha, M, init_pi, max_iter, tol, max_iter_ot, tol_ot, rescale_plan, check_every, use_mixed_precision) {
    .Call(`_rfugw_cpp_fugw_kl_square`, Cx, Cy, wx, wy, reg_marginals, epsilon, alpha, M, init_pi, max_iter, tol, max_iter_ot, tol_ot, rescale_plan, check_every, use_mixed_precision)
}

cpp_fugw_kl_square_batch <- function(Cx_list, wx_list, M_list, Cy, wy, reg_marginals, epsilon, alpha, max_iter, tol, max_iter_ot, tol_ot, rescale_plan, check_every, init_pi_list, n_threads) {
    .Call(`_rfugw_cpp_fugw_kl_square_batch`, Cx_list, wx_list, M_list, Cy, wy, reg_marginals, epsilon, alpha, max_iter, tol, max_iter_ot, tol_ot, rescale_plan, check_every, init_pi_list, n_threads)
}

cpp_sampled_gromov_wasserstein_entropic_square <- function(C1, C2, p, q, nb_p, nb_q, epsilon, max_iter, sinkhorn_max_iter, sinkhorn_tol, symmetric, init_plan, verbose, use_mixed_precision) {
    .Call(`_rfugw_cpp_sampled_gromov_wasserstein_entropic_square`, C1, C2, p, q, nb_p, nb_q, epsilon, max_iter, sinkhorn_max_iter, sinkhorn_tol, symmetric, init_plan, verbose, use_mixed_precision)
}

cpp_sampled_gromov_wasserstein_coords_entropic_square <- function(X1, X2, p, q, nb_p, nb_q, epsilon, max_iter, sinkhorn_max_iter, sinkhorn_tol, metric_code, init_plan, verbose, use_mixed_precision, deterministic_sampling) {
    .Call(`_rfugw_cpp_sampled_gromov_wasserstein_coords_entropic_square`, X1, X2, p, q, nb_p, nb_q, epsilon, max_iter, sinkhorn_max_iter, sinkhorn_tol, metric_code, init_plan, verbose, use_mixed_precision, deterministic_sampling)
}

cpp_srfgw_row_min_direction <- function(Mi, p) {
    .Call(`_rfugw_cpp_srfgw_row_min_direction`, Mi, p)
}

cpp_gw_square_terms_square <- function(C1, C2, G, symmetric = TRUE) {
    .Call(`_rfugw_cpp_gw_square_terms_square`, C1, C2, G, symmetric)
}

cpp_entropic_partial_wasserstein <- function(a, b, M, reg, m, numItermax = 1000L, stopThr = 1e-100, verbose = FALSE, log = FALSE) {
    .Call(`_rfugw_cpp_entropic_partial_wasserstein`, a, b, M, reg, m, numItermax, stopThr, verbose, log)
}

cpp_semirelaxed_fgw_exact_square <- function(M, C1, C2, p, alpha, symmetric, init_plan, max_iter, tol_rel, tol_abs) {
    .Call(`_rfugw_cpp_semirelaxed_fgw_exact_square`, M, C1, C2, p, alpha, symmetric, init_plan, max_iter, tol_rel, tol_abs)
}

cpp_semirelaxed_fgw_cg_square_fast <- function(M, C1, C2, p, alpha, init_plan, max_iter, tol_rel, tol_abs, verbose, use_mixed_precision) {
    .Call(`_rfugw_cpp_semirelaxed_fgw_cg_square_fast`, M, C1, C2, p, alpha, init_plan, max_iter, tol_rel, tol_abs, verbose, use_mixed_precision)
}

cpp_ot_sinkhorn <- function(M, p, q, epsilon, max_iter, tol, use_log) {
    .Call(`_rfugw_cpp_ot_sinkhorn`, M, p, q, epsilon, max_iter, tol, use_log)
}

cpp_ot_emd <- function(M, p, q, max_iter, tol) {
    .Call(`_rfugw_cpp_ot_emd`, M, p, q, max_iter, tol)
}

cpp_ot_sinkhorn_unbalanced <- function(M, a, b, epsilon, rho1, rho2, max_iter, tol, init_plan) {
    .Call(`_rfugw_cpp_ot_sinkhorn_unbalanced`, M, a, b, epsilon, rho1, rho2, max_iter, tol, init_plan)
}

cpp_partial_fgw_exact_square <- function(M, C1, C2, p, q, m, alpha, symmetric, init_plan, max_iter, tol, nb_dummies, lp_max_iter, lp_tol) {
    .Call(`_rfugw_cpp_partial_fgw_exact_square`, M, C1, C2, p, q, m, alpha, symmetric, init_plan, max_iter, tol, nb_dummies, lp_max_iter, lp_tol)
}

cpp_partial_fgw_entropic_square <- function(M, C1, C2, p, q, m, reg, alpha, symmetric, init_plan, max_iter, tol, inner_max_iter, inner_tol, check_every) {
    .Call(`_rfugw_cpp_partial_fgw_entropic_square`, M, C1, C2, p, q, m, reg, alpha, symmetric, init_plan, max_iter, tol, inner_max_iter, inner_tol, check_every)
}

cpp_ucoot_kl <- function(X, Y, wx_samp, wx_feat, wy_samp, wy_feat, reg_marginals, epsilon, M_samp, M_feat, init_pi_samp, init_pi_feat, joint, rescale_plan, max_iter, tol, max_iter_ot, tol_ot, use_warm_start) {
    .Call(`_rfugw_cpp_ucoot_kl`, X, Y, wx_samp, wx_feat, wy_samp, wy_feat, reg_marginals, epsilon, M_samp, M_feat, init_pi_samp, init_pi_feat, joint, rescale_plan, max_iter, tol, max_iter_ot, tol_ot, use_warm_start)
}

